version: '3.9'

services:
  app:
    container_name: web-atrio-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=WebAtrioAppdb;Username=postgres;Password=example;
    depends_on:
      - db
    ports:
      - "8000:80"

  db:
    container_name: web-atrio-db-postgres
    image: postgres:16.3
    environment:
      POSTGRES_DB: WebAtrioAppdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: